name: Post to X
on:
  schedule:
    - cron: "0 */8 * * *"   # cada 8 horas (3 tweets/día)
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - env:
          X_BEARER: ${{ secrets.X_BEARER }}
        run: python bot.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Marcar tweet usado"
